
// Resources

export const FETCH_FOOTER_SUCCESS = "FETCH_FOOTER_SUCCESS";
export const FETCH_MENU_RESOURCE_SUCCESS = "FETCH_MENU_SUCCESS";
export const REFETCH_LAYOUT_RESOURCES = "REFETCH_LAYOUT_RESOURCES";
export const REFETCH_LOGIN_RESOURCES = "REFETCH_LOGIN_RESOURCES";
export const REFETCH_REGISTER_RESOURCES = "REFETCH_REGISTER_RESOURCES";
export const REFETCH_FORGOTPASSWORD_RESOURCES = "REFETCH_FORGOTPASSWORD_RESOURCES";
export const REFETCH_RESETPASSWORD_RESOURCES = "REFETCH_RESETPASSWORD_RESOURCES";
export const REFETCH_PLAYERPROFILE_RESOURCES = "REFETCH_PLAYERPROFILE_RESOURCES";
export const REFETCH_PLAYERREPUTATION_RESOURCES = "REFETCH_PLAYERREPUTATION_RESOURCES";
export const REFETCH_SEARCHGROUP_RESOURCES = "REFETCH_SEARCHGROUP_RESOURCES";
export const REFETCH_CREATEGROUP_RESOURCES = "REFETCH_CREATEGROUP_RESOURCES";
export const REFETCH_VIEWGROUP_RESOURCES = "REFETCH_VIEWGROUP_RESOURCES";
export const REFETCH_SETTINGS_RESOURCES = "REFETCH_SETTINGS_RESOURCES";
export const REFETCH_RANKSANDTITLES_RESOURCES = "REFETCH_RANKSANDTITLES_RESOURCES";
export const REFETCH_REVIEW_RESOURCES = "REFETCH_REVIEW_RESOURCES";
export const REFETCH_SHOWCASE_RESOURCES = "REFETCH_SHOWCASE_RESOURCES";
export const FETCH_LOGIN_RESOURCE_SUCCESS = "FETCH_LOGIN_RESOURCE_SUCCESS";
export const FETCH_REGISTER_RESOURCE_SUCCESS = "FETCH_REGISTER_RESOURCE_SUCCESS";
export const FETCH_FORGOTPASSWORD_RESOURCE_SUCCESS = "FETCH_FORGOTPASSWORD_RESOURCE_SUCCESS";
export const FETCH_RESETPASSWORD_RESOURCE_SUCCESS = "FETCH_RESETPASSWORD_RESOURCE_SUCCESS";
export const FETCH_PLAYERPROFILE_RESOURCE_SUCCESS = "FETCH_PLAYERPROFILE_RESOURCE_SUCCESS";
export const FETCH_PLAYERREPUTATION_RESOURCE_SUCCESS = "FETCH_PLAYERREPUTATION_RESOURCE_SUCCESS";
export const FETCH_SEARCHGROUP_RESOURCE_SUCCESS = "FETCH_SEARCHGROUP_RESOURCE_SUCCESS";
export const FETCH_CREATEGROUP_RESOURCE_SUCCESS = "FETCH_CREATEGROUP_RESOURCE_SUCCESS";
export const FETCH_VIEWGROUP_RESOURCE_SUCCESS = "FETCH_VIEWGROUP_RESOURCE_SUCCESS";
export const FETCH_SETTINGS_RESOURCE_SUCCESS = "FETCH_SETTINGS_RESOURCE_SUCCESS";
export const FETCH_RANKSANDTITLES_RESOURCE_SUCCESS = "FETCH_RANKSANDTITLES_RESOURCE_SUCCESS";
export const FETCH_REVIEW_RESOURCE_SUCCESS = "FETCH_REVIEW_RESOURCE_SUCCESS";
export const FETCH_SHOWCASE_RESOURCE_SUCCESS = "FETCH_SHOWCASE_RESOURCE_SUCCESS";

export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAILED = "LOGIN_REQUEST_FAILED";
export const LOGIN_CAPTCHA_REQUEST_SUCCESS = "LOGIN_CAPTCHA_REQUEST_SUCCESS";
export const LOGIN_USERINFO_SUCCESS = "LOGIN_USERINFO_SUCCESS";
export const LOGIN_USERINFO_FAILED = "LOGIN_USERINFO_FAILED";
export const LOGIN_REFRESHTOKEN_SUCCESS = "LOGIN_REFRESHTOKEN_SUCCESS";
export const LOGIN_REFRESHTOKEN_FAILED = "LOGIN_REFRESHTOKEN_FAILED";
export const LOGIN_REVOKE_ACCESS_TOKEN = "LOGIN_REVOKE_ACCESS_TOKEN";
export const LOGIN_REVOKE_REFRESH_TOKEN = "LOGIN_REVOKE_REFRESH_TOKEN";
export const LOGIN_UNMOUNT = "LOGIN_UNMOUNT";
export const LOGIN_REQUEST_TOGGLE = "LOGIN_REQUEST_TOGGLE";

export const REGISTER_REQUEST_TOGGLE = "REGISTER_REQUEST_STARTED";
export const REGISTER_USERNAME_IN_USE_SUCCESS = "REGISTER_USERNAME_IN_USE_SUCCESS";
export const REGISTER_MOUNT = "REGISTER_MOUNT";

export const ACTIVATE_ACCOUNT_SUCCESS = "ACTIVATE_ACCOUNT_SUCCESS";
export const ACTIVATE_ACCOUNT_FAILED = "ACTIVATE_ACCOUNT_FAILED";
export const ACTIVATE_ACCOUNT_MOUNT = "ACTIVATE_ACCOUNT_MOUNT";

export const FORGOT_PASSWORD_MOUNT = "FORGOT_PASSWORD_MOUNT";
export const FORGOT_PASSWORD_REQUEST_TOGGLE = "FORGOT_PASSWORD_REQUEST_TOGGLE";

export const RESET_PASSWORD_MOUNT = "RESET_PASSWORD_MOUNT";
export const RESET_PASSWORD_REQUEST_TOGGLE = "RESET_PASSWORD_REQUEST_TOGGLE";

export const PLAYERPROFILE_REQUEST_TOGGLE = "PLAYERPROFILE_REQUEST_TOGGLE";
export const PLAYERPROFILE_READ_SUCCESS = "PLAYERPROFILE_READ_SUCCESS";
export const PLAYERPROFILE_SAVE_SUCCESS = "PLAYERPROFILE_SAVE_SUCCESS";
export const PLAYERPROFILE_MOUNT = "PLAYERPROFILE_MOUNT";
export const PLAYERPROFILE_REMOVE_ACCOUNT = "PLAYERPROFILE_REMOVE_ACCOUNT";
export const PLAYERPROFILE_REQUEST_AVATAR = "PLAYERPROFILE_REQUEST_AVATAR";
export const PLAYERPROFILE_REQUEST_AVATAR_SUCCESS = "PLAYERPROFILE_REQUEST_AVATAR_SUCCESS";
export const PLAYERPROFILE_REQUEST_AVATAR_FAILED = "PLAYERPROFILE_REQUEST_AVATAR_FAILED";
export const PLAYERPROFILE_PICTURE_CHANGED = "PLAYERPROFILE_PICTURE_CHANGED";
export const PLAYERPROFILE_EDITING_TOGGLE = "PLAYERPROFILE_EDITING_TOGGLE";

export const DATA_TIMEZONES_REQUEST_TOGGLE = "DATA_TIMEZONES_REQUEST_TOGGLE";
export const DATA_TIMEZONES_SUCCESS = "DATA_TIMEZONES_SUCCESS";
export const DATA_TIMEZONES_REFETCH = "DATA_TIMEZONES_REFETCH";
export const DATA_TIMEZONES_CLEAR = "DATA_TIMEZONES_CLEAR";

export const DATA_PLAYERTYPES_REQUEST_TOGGLE = "DATA_PLAYERTYPES_REQUEST_TOGGLE";
export const DATA_PLAYERTYPES_SUCCESS = "DATA_PLAYERTYPES_SUCCESS";
export const DATA_PLAYERTYPES_REFETCH = "DATA_PLAYERTYPES_REFETCH";
export const DATA_PLAYERTYPES_CLEAR = "DATA_PLAYERTYPES_CLEAR";

export const DATA_LANGUAGES_REQUEST_TOGGLE = "DATA_LANGUAGES_REQUEST_TOGGLE";
export const DATA_LANGUAGES_SUCCESS = "DATA_LANGUAGES_SUCCESS";
export const DATA_LANGUAGES_REFETCH = "DATA_LANGUAGES_REFETCH";
export const DATA_LANGUAGES_CLEAR = "DATA_LANGUAGES_CLEAR";

export const DATA_GAMES_REQUEST_TOGGLE = "DATA_GAMES_REQUEST_TOGGLE";
export const DATA_GAMES_SUCCESS = "DATA_GAMES_SUCCESS";
export const DATA_GAMES_REFETCH = "DATA_GAMES_REFETCH";
export const DATA_GAMES_CLEAR = "DATA_GAMES_CLEAR";
export const DATA_GAMES_CREATE_TAG = "DATA_GAMES_CREATE_TAG";

export const DATA_AGES_REQUEST_TOGGLE = "DATA_AGES_REQUEST_TOGGLE";
export const DATA_AGES_SUCCESS = "DATA_AGES_SUCCESS";
export const DATA_AGES_REFETCH = "DATA_AGES_REFETCH";
export const DATA_AGES_CLEAR = "DATA_AGES_CLEAR";

export const DATA_PLAYSTYLES_REQUEST_TOGGLE = "DATA_PLAYSTYLES_REQUEST_TOGGLE";
export const DATA_PLAYSTYLES_SUCCESS = "DATA_PLAYSTYLES_SUCCESS";
export const DATA_PLAYSTYLES_REFETCH = "DATA_PLAYSTYLES_REFETCH";
export const DATA_PLAYSTYLES_CLEAR = "DATA_PLAYSTYLES_CLEAR";

export const DATA_COMMUNICATIONS_REQUEST_TOGGLE = "DATA_COMMUNICATIONS_REQUEST_TOGGLE";
export const DATA_COMMUNICATIONS_SUCCESS = "DATA_COMMUNICATIONS_SUCCESS";
export const DATA_COMMUNICATIONS_REFETCH = "DATA_COMMUNICATIONS_REFETCH";
export const DATA_COMMUNICATIONS_CLEAR = "DATA_COMMUNICATIONS_CLEAR";

export const REPUTATION_REQUEST_TOGGLE = "REPUTATION_REQUEST_TOGGLE";
export const REPUTATION_SUCCESS = "REPUTATION_SUCCESS";
export const REPUTATION_MOUNT = "REPUTATION_MOUNT";

export const GROUP_SEARCH_REQUEST_TOGGLE = "GROUP_SEARCH_REQUEST_TOGGLE";
export const GROUP_SEARCH_SUCCESS = "GROUP_SEARCH_SUCCESS";
export const GROUP_SEARCH_MOUNT = "GROUP_SEARCH_MOUNT";
export const GROUP_FROMDATE_SET = "GROUP_FROMDATE_SET";
export const GROUP_TODATE_SET = "GROUP_TODATE_SET";

export const GROUP_CREATE_MOUNT = "GROUP_CREATE_MOUNT";
export const GROUP_CREATE_REQUEST_TOGGLE = "GROUP_CREATE_REQUEST_TOGGLE";
export const GROUP_SET_DATE = "GROUP_SET_DATE";

export const GROUP_BYID_REQUEST_TOGGLE = "GROUP_BYID_REQUEST_TOGGLE";
export const GROUP_BYID_SUCCESS = "GROUP_BYID_SUCCESS";
export const GROUP_BYID_MOUNT = "GROUP_BYID_MOUNT";

export const GROUP_DELETE_SUCCESS = "GROUP_DELETE_SUCCESS";

export const GROUP_CHAT_SUCCESS = "GROUP_CHAT_SUCCESS";
export const GROUP_CHAT_SIGNALR_SUCCESS = "GROUP_CHAT_SIGNALR_SUCCESS";
export const GROUP_CHAT_CLEAR = "GROUP_CHAT_CLEAR";

export const GROUP_REVIEW_REQUEST_TOGGLE = "GROUP_REVIEW_REQUEST_TOGGLE";
export const GROUP_REVIEW_SUCCESS = "GROUP_REVIEW_SUCCESS";
export const GROUP_REVIEW_SEND_SUCCESS = "GROUP_REVIEW_SEND_SUCCESS";
export const GROUP_REVIEW_CLEAR = "GROUP_REVIEW_CLEAR";

export const GROUP_IMAGE_CHANGED = "GROUP_IMAGE_CHANGED";

export const PLAYER_CONFIGURATION_MOUNT = "PLAYER_CONFIGURATION_MOUNT";
export const PLAYER_CONFIGURATION_REQUEST_TOGGLE = "PLAYER_CONFIGURATION_REQUEST_TOGGLE";
export const PLAYER_CONFIGURATION_SUCCESS = "PLAYER_CONFIGURATION_SUCCESS";

export const PAGE_CHANGE = "PAGE_CHANGE";

export const NOTIFICATION_MOUNT = "NOTIFICATION_MOUNT";
export const NOTIFICATION_SUCCESS = "NOTIFICATION_SUCCESS";
export const NOTIFICATION_REQUEST_TOGGLE = "NOTIFICATION_REQUEST_TOGGLE";
export const NOTIFICATION_UNREAD = "NOTIFICATION_UNREAD";
export const NOTIFICATION_CLEAR = "NOTIFICATION_CLEAR";

export const SHOW = 'loading-bar/SHOW'
export const HIDE = 'loading-bar/HIDE'
export const RESET = 'loading-bar/RESET'

export const IGNORE = "IGNORE";
